import {
  AuthorizationError,
  InvalidAuthTypeError,
  InvalidHostConfigError,
  UnexpectedAuthTypeError,
  auth_default,
  checkForCrossDomainRequest,
  determineAuthType,
  getAccessToken,
  getRestCallAuthParams,
  getWebResourceAuthParams,
  getWebSocketAuthParams,
  handleAuthenticationError,
  isHostCrossOrigin,
  isWindows,
  logout,
  registerAuthModule,
  registerHostConfig,
  serializeHostConfig,
  setDefaultHostConfig,
  toValidLocationUrl,
  toValidWebsocketLocationUrl,
  unregisterHostConfig
} from "./FKDGGR2O.js";
import "./3RGGGGAR.js";
import "./2ZQ3ZX7F.js";
export {
  AuthorizationError,
  InvalidAuthTypeError,
  InvalidHostConfigError,
  UnexpectedAuthTypeError,
  checkForCrossDomainRequest,
  auth_default as default,
  determineAuthType,
  getAccessToken,
  getRestCallAuthParams,
  getWebResourceAuthParams,
  getWebSocketAuthParams,
  handleAuthenticationError,
  isHostCrossOrigin,
  isWindows,
  logout,
  registerAuthModule,
  registerHostConfig,
  serializeHostConfig,
  setDefaultHostConfig,
  toValidLocationUrl,
  toValidWebsocketLocationUrl,
  unregisterHostConfig
};
