import {
  AuthorizationError,
  InvalidAuthTypeError,
  InvalidHostConfigError,
  UnexpectedAuthTypeError,
  auth_default,
  checkForCrossDomainRequest,
  getRestCallAuthParams,
  getWebResourceAuthParams,
  getWebSocketAuthParams,
  handleAuthenticationError,
  isHostCrossOrigin,
  isWindows,
  logout,
  registerAuthModule,
  setDefaultHostConfig,
  toValidEnigmaLocationUrl,
  toValidLocationUrl,
  toValidWebsocketLocationUrl
} from "./VMS4MOCI.mjs";
import "./VSY5YIQY.mjs";
export {
  AuthorizationError,
  InvalidAuthTypeError,
  InvalidHostConfigError,
  UnexpectedAuthTypeError,
  checkForCrossDomainRequest,
  auth_default as default,
  getRestCallAuthParams,
  getWebResourceAuthParams,
  getWebSocketAuthParams,
  handleAuthenticationError,
  isHostCrossOrigin,
  isWindows,
  logout,
  registerAuthModule,
  setDefaultHostConfig,
  toValidEnigmaLocationUrl,
  toValidLocationUrl,
  toValidWebsocketLocationUrl
};
