//#region src/platform/platform-types.d.ts
/** Data is accessible on `/resources/autogenerated/product-info.json` on any deployment */
type ProductInfo = {
  composition?: {
    contentHash?: string;
    senseId: string;
    releaseLabel?: string;
    originalClassName?: string;
    productName?: string;
    version?: string;
    copyrightYearRange?: string;
    deploymentEnvironment?: string;
    deploymentType?: "qliksenseserver" | "qliksensedesktop" | "QlikSenseMobile" | "qlikcloudservices" | "cloud-console";
    provider?: string;
  };
  externalUrls: {
    contentHash?: string;
    originalClassName?: string;
    personalUpgradeBase: string;
    cloudUploadUrl: string;
    serverHelpBaseUrl: string;
    personalHelpBaseUrl: string;
    personalUpgradeUrl: string;
    qlikWebPageUrl: string;
    cloudBaseUrl: string;
  };
};
//#endregion
export { ProductInfo as t };