import { b as ApiCallOptions } from "../chunks/auth-types-DVvka7Hz.js";
declare namespace automations_d_exports {
  export { AutomationDetailRequestObject, AutomationDetailResponseObject, AutomationDetailUpdateRequestObject, AutomationList, AutomationListObject, AutomationUsageObject, AutomationsAPI, ChangeOwnerAutomationHttpError, ChangeOwnerAutomationHttpResponse, ChangeSpaceAutomationHttpError, ChangeSpaceAutomationHttpResponse, CopyAutomationHttpError, CopyAutomationHttpResponse, CreateAutomationHttpError, CreateAutomationHttpResponse, CreateAutomationRunHttpError, CreateAutomationRunHttpResponse, DeleteAutomationHttpError, DeleteAutomationHttpResponse, DisableAutomationHttpError, DisableAutomationHttpResponse, EnableAutomationHttpError, EnableAutomationHttpResponse, Error, ErrorResponse, ExportAutomationRunHttpError, ExportAutomationRunHttpResponse, GetAutomationHttpError, GetAutomationHttpResponse, GetAutomationRunDebugHttpError, GetAutomationRunDebugHttpResponse, GetAutomationRunHttpError, GetAutomationRunHttpResponse, GetAutomationRunsHttpError, GetAutomationRunsHttpResponse, GetAutomationsHttpError, GetAutomationsHttpResponse, GetAutomationsSettingsHttpError, GetAutomationsSettingsHttpResponse, GetAutomationsUsageMetricsHttpError, GetAutomationsUsageMetricsHttpResponse, Links, MoveAutomationHttpError, MoveAutomationHttpResponse, PaginationLink, RetryAutomationRunHttpError, RetryAutomationRunHttpResponse, RunDetailRequestObject, RunDetailResponseObject, RunList, RunListObject, ScheduleRequestObject, ScheduleResponseObject, SettingsObject, StopAutomationRunHttpError, StopAutomationRunHttpResponse, UpdateAutomationHttpError, UpdateAutomationHttpResponse, UpdateAutomationsSettingsHttpError, UpdateAutomationsSettingsHttpResponse, UsageList, UsageObject, changeOwnerAutomation, changeSpaceAutomation, clearCache, copyAutomation, createAutomation, createAutomationRun, automationsExport as default, deleteAutomation, disableAutomation, enableAutomation, exportAutomationRun, getAutomation, getAutomationRun, getAutomationRunDebug, getAutomationRuns, getAutomations, getAutomationsSettings, getAutomationsUsageMetrics, moveAutomation, retryAutomationRun, stopAutomationRun, updateAutomation, updateAutomationsSettings };
}
type AutomationDetailRequestObject = {
  /** The description of the automation */description?: string; /** Maximum number of concurrent runs allowed for this automation. The maximum value is defined in automations settings. */
  maxConcurrentRuns?: number; /** The name of the automation. */
  name: string;
  schedules?: ScheduleRequestObject[]; /** The unique identifier of the space in which the automation is created. */
  spaceId?: string; /** The workspace generated by the Qlik Automate editor. */
  workspace?: unknown;
};
type AutomationDetailResponseObject = {
  /** A list of connectors that were detected in the workspace. This includes connectors present in blocks that are not connected to other blocks. Order of GUIDs is not guaranteed. */readonly connectorIds?: string[];
  readonly createdAt?: string; /** The description of the automation. */
  description?: string; /** A list of endpoints that were detected in the workspace. This includes endpoints present in blocks that are not connected to other blocks. Order of GUIDs is not guaranteed. */
  readonly endpointIds?: string[]; /** Execution token required to authorize the execution of the automation. */
  readonly executionToken?: string;
  readonly id?: string;
  lastRun?: RunDetailResponseObject; /** The date and time when the last automation run was finished. */
  readonly lastRunAt?: string; /** The status of the last run of the automation. */
  readonly lastRunStatus?: "failed" | "finished" | "finished with warnings" | "must stop" | "not started" | "paused" | "running" | "starting" | "stopped" | "exceeded limit"; /** Maximum number of concurrent runs allowed for this automation. */
  readonly maxConcurrentRuns?: number; /** The name of the automation. */
  name?: string; /** The unique identifier of the owner of the automation. */
  readonly ownerId?: string; /** Defines how the automation run is started. */
  readonly runMode?: "manual" | "scheduled" | "triggered" | "webhook";
  schedules?: ScheduleResponseObject[]; /** A list of snippets that were detected in the workspace. This includes snippet blocks that are not connected to other blocks. Order of GUIDs is not guaranteed. */
  readonly snippetIds?: string[]; /** The unique identifier of the space that contains the automation. */
  readonly spaceId?: string; /** The state of the automation. */
  state?: "available" | "unavailable" | "disabled";
  readonly updatedAt?: string; /** The workspace generated by the Qlik Automate editor. */
  workspace?: unknown;
};
type AutomationDetailUpdateRequestObject = {
  /** The description of the automation */description?: string; /** Maximum number of concurrent runs allowed for this automation. The maximum value is defined in automations settings. */
  maxConcurrentRuns?: number; /** The name of the automation. */
  name?: string;
  schedules?: ScheduleRequestObject[]; /** The workspace generated by the Qlik Automate editor. */
  workspace?: unknown;
};
type AutomationList = {
  data?: AutomationListObject[];
  links?: Links;
};
type AutomationListObject = {
  /** A list of connectors that were detected the workspace. This includes Connectors present in blocks which are not connected to other blocks. Order of guids is not guaranteed. */readonly connectorIds?: string[];
  readonly createdAt?: string; /** The description of the automation. */
  description?: string; /** Duration of the last run, indicated in seconds. Calculated from start and stop times. */
  readonly duration?: number; /** A list of endpoints that were detected inside the workspace. This includes Endpoints present in blocks which are not connected to other blocks. Order of guids is not guaranteed. */
  readonly endpointIds?: string[]; /** Execution token required to authorize the execution of the automation. */
  readonly executionToken?: string; /** The unique identifier for the automation. */
  readonly id?: string;
  lastRun?: RunDetailResponseObject; /** The date and time when the last automation run was finished. */
  readonly lastRunAt?: string; /** The status of the last run of the automation. */
  readonly lastRunStatus?: "failed" | "finished" | "finished with warnings" | "must stop" | "not started" | "paused" | "running" | "starting" | "stopped" | "exceeded limit"; /** Maximum number of concurrent runs allowed for automation. */
  readonly maxConcurrentRuns?: number; /** The name of the automation. */
  name?: string; /** The unique identifier of the owner of the automation. */
  readonly ownerId?: string; /** Defines how the automation run is started. */
  readonly runMode?: "manual" | "scheduled" | "triggered" | "webhook"; /** A list of snippets that were detected in the workspace. This includes snippet blocks that are not connected to other blocks. Order of GUIDs is not guaranteed. */
  readonly snippetIds?: string[]; /** The unique identifier of the space that contains the automation. */
  readonly spaceId?: string; /** The state of the automation. */
  state?: "available" | "unavailable" | "disabled";
  readonly updatedAt?: string; /** The workspace contains the JSON representation of the used blocks */
  readonly workspace?: unknown;
};
type AutomationUsageObject = {
  /** The unique identifier for the automation. */guid?: string; /** The name for the automation. */
  name?: string; /** The unique identifier for the user who owns the automation */
  ownerId?: string;
};
type Error = {
  /** The unique code for the error */code: string; /** May be used to provide additional details */
  detail?: string; /** A summary of what went wrong */
  title: string;
};
type ErrorResponse = {
  errors?: Error[]; /** A way to trace the source of the error. */
  traceId?: string;
};
type Links = {
  next?: PaginationLink;
  prev?: PaginationLink;
};
type PaginationLink = {
  /** The URL to a resource request */href?: string;
};
type RunDetailRequestObject = {
  /** The source that triggers the automation will set the context. */context: "api"; /** The unique identifier of the run. */
  readonly id?: string;
};
type RunDetailResponseObject = {
  /** Indicates if this automation run is archived. */readonly archived?: boolean; /** The source that triggers the automation will set the context. Certain contexts impact the execution of an automation (for example, The "test_run" context will not process all results when listing items). */
  context?: "test_run" | "editor" | "detail" | "api_sync" | "api_async" | "webhook" | "lookup";
  readonly createdAt?: string; /** List of errors that occurred during the automation run. */
  error?: unknown[]; /** The unique identifier of the user who executed the automation run. */
  readonly executedById?: string; /** The unique identifier of the run. */
  readonly id?: string; /** Indicates if this automation run is archived. */
  readonly isArchived?: boolean; /** Indicates if this automation run is a test run. */
  readonly isTestRun?: boolean;
  metrics?: {
    /** List of blocks used during execution. Note: this list currently only contains endpointBlocks and snippetBlocks */blocks?: {
      /** API calls to external resources made by the current block. */apiCalls?: number; /** Unique identifier for the connector used within the block of the execution. */
      connectorId?: string; /** Unique identifier for the endpoint block used within the execution. */
      endpointId?: string; /** Total amount of received bytes sent by the current block. */
      rxBytes: number; /** Unique identifier for the snippet block used within the execution. */
      snippetId?: string; /** Total amount of sent bytes sent by the current block. */
      txBytes: number; /** Type of the block. */
      type: "snippetBlock" | "endpointBlock";
    }[];
    network?: {
      /** The number of received bytes. */rxBytes?: number; /** The number of received bytes. */
      txBytes?: number;
    }; /** The number of API calls made. */
    totalApiCalls?: number;
  }; /** The unique identifier of the owner of the automation run. */
  readonly ownerId?: string; /** The date and time at which the automation run is scheduled to start. */
  readonly scheduledStartTime?: string; /** The unique identifier of the space in which the automation run is created. */
  readonly spaceId?: string; /** The date and time at which the automation run started. */
  readonly startTime?: string; /** The current status of the automation run. */
  status?: "failed" | "finished" | "finished with warnings" | "must stop" | "not started" | "running" | "starting" | "stopped" | "exceeded limit" | "queued"; /** The date and time at which the automation run stopped. */
  readonly stopTime?: string; /** Indicates if this automation run is a test run. */
  readonly testRun?: boolean; /** The title of the automation run. */
  title?: string;
  readonly updatedAt?: string;
};
type RunList = {
  data?: RunListObject[];
  links?: Links;
};
type RunListObject = {
  /** Indicates if this automation run is archived. */readonly archived?: boolean; /** The context set by the source that triggers the automation. */
  context?: "test_run" | "editor" | "detail" | "api_sync" | "api_async" | "webhook" | "lookup";
  readonly createdAt?: string; /** Duration of the run, indicated in seconds. Calculated from start and stop times */
  readonly duration?: number; /** List of errors that occurred during the automation run. */
  error?: unknown[]; /** The unique identifier of the user who executed the automation run. */
  readonly executedById?: string;
  readonly id?: string; /** Indicates if this automation run is archived. */
  readonly isArchived?: boolean; /** Indicates if this automation run is a test run. */
  readonly isTestRun?: boolean; /** The unique identifier of the owner of the automation run. */
  readonly ownerId?: string; /** The date and time at which the automation run is scheduled to start. */
  readonly scheduledStartTime?: string; /** The unique identifier of the space in which the automation run is created. */
  readonly spaceId?: string; /** The date and time at which the automation run started. */
  readonly startTime?: string; /** The current status of the automation run. */
  status?: "failed" | "finished" | "finished with warnings" | "must stop" | "not started" | "running" | "starting" | "stopped" | "exceeded limit" | "queued"; /** The date and time at which the automation run stopped. */
  readonly stopTime?: string; /** Indicates if this automation run is a test run. */
  readonly testRun?: boolean; /** The title of the automation run. */
  title?: string;
  readonly updatedAt?: string;
};
type ScheduleRequestObject = {
  /** time in seconds. */interval?: number; /** The date and time when the schedule becomes active. */
  startAt?: string; /** The date and time until the schedule is active. */
  stopAt?: string; /** The timezone applied to the start and end times. */
  timezone?: string;
};
type ScheduleResponseObject = {
  readonly id?: string; /** time in seconds. */
  interval?: number;
  lastStartedAt?: string;
  startAt?: string;
  stopAt?: string;
  timezone?: string;
};
type SettingsObject = {
  /** Maximum number of concurrent runs allowed per automation. */maxConcurrentRunsPerAutomation?: number;
};
type UsageList = {
  data?: UsageObject[];
};
type UsageObject = {
  automation?: AutomationUsageObject; /** The date for the metric */
  date: string; /** The name for the metric */
  name: "runs" | "scheduledRun" | "triggeredRun" | "webhookRuns" | "duration" | "bandwidthIn" | "bandwidthOut"; /** The value count of the metric */
  value: number;
};
/**
 * Retrieves a list of the automations that the requesting user has access to.
 *
 * @param query an object with query parameters
 * @throws GetAutomationsHttpError
 */
declare function getAutomations(query: {
  /** Allowed filters: `name`, `runMode`, `lastRunStatus`, `ownerId`, `spaceId`. */filter?: string; /** The number of automations to retrieve. */
  limit?: number; /** When true, list all automations. Restricted to tenant admins and analytics admins. */
  listAll?: boolean; /** The field to sort by, with +- prefix indicating sort order. (`?sort=-name` => sort on the `name` field using descending order). */
  sort?: "id" | "name" | "runMode" | "state" | "createdAt" | "updatedAt" | "lastRunAt" | "lastRunStatus" | "+id" | "+name" | "+runMode" | "+state" | "+createdAt" | "+updatedAt" | "+lastRunAt" | "+lastRunStatus" | "-id" | "-name" | "-runMode" | "-state" | "-createdAt" | "-updatedAt" | "-lastRunAt" | "-lastRunStatus" | "maxConcurrentRuns" | "+maxConcurrentRuns" | "-maxConcurrentRuns";
}, options?: ApiCallOptions): Promise<GetAutomationsHttpResponse>;
type GetAutomationsHttpResponse = {
  data: AutomationList;
  headers: Headers;
  status: 200;
  prev?: (options?: ApiCallOptions) => Promise<GetAutomationsHttpResponse>;
  next?: (options?: ApiCallOptions) => Promise<GetAutomationsHttpResponse>;
};
type GetAutomationsHttpError = {
  data: ErrorResponse;
  headers: Headers;
  status: 400 | 401 | 403 | 500 | 503;
};
/**
 * Creates a new automation. The requesting user must be assigned the `AutomationCreator` role or have at least one of the following scopes: `automations`, `admin.automations`, `automations.private` or `automations.shared`.
 *
 * @param body an object with the body content
 * @throws CreateAutomationHttpError
 */
declare function createAutomation(body: AutomationDetailRequestObject, options?: ApiCallOptions): Promise<CreateAutomationHttpResponse>;
type CreateAutomationHttpResponse = {
  data: AutomationDetailResponseObject;
  headers: Headers;
  status: 201;
};
type CreateAutomationHttpError = {
  data: ErrorResponse;
  headers: Headers;
  status: 400 | 401 | 403 | 500 | 503;
};
/**
 * Retrieves the global automation settings for the tenant.
 *
 * @throws GetAutomationsSettingsHttpError
 */
declare function getAutomationsSettings(options?: ApiCallOptions): Promise<GetAutomationsSettingsHttpResponse>;
type GetAutomationsSettingsHttpResponse = {
  data: SettingsObject;
  headers: Headers;
  status: 200;
};
type GetAutomationsSettingsHttpError = {
  data: ErrorResponse;
  headers: Headers;
  status: 400 | 401 | 403 | 500 | 503;
};
/**
 * Updates the global automation settings for the tenant.
 *
 * @param body an object with the body content
 * @throws UpdateAutomationsSettingsHttpError
 */
declare function updateAutomationsSettings(body: SettingsObject, options?: ApiCallOptions): Promise<UpdateAutomationsSettingsHttpResponse>;
type UpdateAutomationsSettingsHttpResponse = {
  data: SettingsObject;
  headers: Headers;
  status: 200;
};
type UpdateAutomationsSettingsHttpError = {
  data: ErrorResponse;
  headers: Headers;
  status: 400 | 401 | 403 | 409 | 500 | 503;
};
/**
 * Retrieves paginated usage metrics for automations. The requesting user must be assigned the `TenantAdmin` or `AnalyticsAdmin` role.
 *
 * @param query an object with query parameters
 * @throws GetAutomationsUsageMetricsHttpError
 */
declare function getAutomationsUsageMetrics(query: {
  /** If specified, result will be broken apart for each automation */breakdownBy?: string;
  /** Indicates how the metrics should be filtered using a SCIM-style expression. Available parameters:
   * - name (specify one or more enums to return specific metrics. Supported enum values: `runs`, `scheduledRuns`, `triggeredRuns`, `webhookRuns`, `duration`, `bandwidthIn`, `bandwidthOut`)
   * - date (return a metric for a specific date or range of dates, e.g. "2025-08-01") */
  filter: string;
}, options?: ApiCallOptions): Promise<GetAutomationsUsageMetricsHttpResponse>;
type GetAutomationsUsageMetricsHttpResponse = {
  data: UsageList;
  headers: Headers;
  status: 200;
};
type GetAutomationsUsageMetricsHttpError = {
  data: ErrorResponse;
  headers: Headers;
  status: 400 | 401 | 403 | 500 | 503;
};
/**
 * Deletes an automation. The requesting user must meet at least one of the following conditions:
 * - be the owner of the automation
 * - be assigned one of the following roles: `AnalyticsAdmin`, `TenantAdmin`
 * - have at least one of the following scopes: `admin.automations`, `admin.automations:strict`, `automations.private`, or `automations.shared`
 *
 * @param id The unique identifier for the automation.
 * @throws DeleteAutomationHttpError
 */
declare function deleteAutomation(id: string, options?: ApiCallOptions): Promise<DeleteAutomationHttpResponse>;
type DeleteAutomationHttpResponse = {
  data: void;
  headers: Headers;
  status: 204;
};
type DeleteAutomationHttpError = {
  data: ErrorResponse;
  headers: Headers;
  status: 401 | 403 | 404 | 500 | 503;
};
/**
 * Retrieves the full definition of an automation. The requesting user must be the owner of the automation and either be assigned one of the roles: `AutomationsCreator`, `TenantAdmin` or have at least one of the following scopes (depending on whether the automation is in a private or shared space): `automations`, `automations.private` or `automations.shared`.
 *
 * @param id The unique identifier for the automation.
 * @throws GetAutomationHttpError
 */
declare function getAutomation(id: string, options?: ApiCallOptions): Promise<GetAutomationHttpResponse>;
type GetAutomationHttpResponse = {
  data: AutomationDetailResponseObject;
  headers: Headers;
  status: 200;
};
type GetAutomationHttpError = {
  data: ErrorResponse;
  headers: Headers;
  status: 400 | 401 | 403 | 404 | 500 | 503;
};
/**
 * Updates the full definition of an automation. The requesting user must be the owner of the automation and either be assigned the `AutomationCreator` role or have at least one of the following scopes: `automations`, `admin.automations`, `automations.private` or `automations.shared`.
 *
 * @param id The unique identifier for the automation.
 * @param body an object with the body content
 * @throws UpdateAutomationHttpError
 */
declare function updateAutomation(id: string, body: AutomationDetailUpdateRequestObject, options?: ApiCallOptions): Promise<UpdateAutomationHttpResponse>;
type UpdateAutomationHttpResponse = {
  data: AutomationDetailResponseObject;
  headers: Headers;
  status: 200;
};
type UpdateAutomationHttpError = {
  data: ErrorResponse;
  headers: Headers;
  status: 400 | 401 | 403 | 404 | 409 | 500 | 503;
};
/**
 * Changes the owner of an automation to another user. This action removes the history and change logs of this automation. All linked connections used in the automation are detached and not moved to the new owner. The requesting user must be assigned one of the following roles: `TenantAdmin`, `AnalyticsAdmin` or have at least one of the following scopes: `admin.automations`, `admin.automations:strict`.
 *
 * @param id The unique identifier for the automation.
 * @param body an object with the body content
 * @throws ChangeOwnerAutomationHttpError
 */
declare function changeOwnerAutomation(id: string, body: {
  /** The unique identifier of the new owner. */userId: string;
}, options?: ApiCallOptions): Promise<ChangeOwnerAutomationHttpResponse>;
type ChangeOwnerAutomationHttpResponse = {
  data: void;
  headers: Headers;
  status: 204;
};
type ChangeOwnerAutomationHttpError = {
  data: ErrorResponse;
  headers: Headers;
  status: 400 | 401 | 403 | 404 | 500 | 503;
};
/**
 * Changes the space of an automation by specifying a new space.
 *
 * @param id The unique identifier for the automation.
 * @param body an object with the body content
 * @throws ChangeSpaceAutomationHttpError
 */
declare function changeSpaceAutomation(id: string, body: {
  /** The unique identifier of the new space. */spaceId: string;
}, options?: ApiCallOptions): Promise<ChangeSpaceAutomationHttpResponse>;
type ChangeSpaceAutomationHttpResponse = {
  data: void;
  headers: Headers;
  status: 204;
};
type ChangeSpaceAutomationHttpError = {
  data: ErrorResponse;
  headers: Headers;
  status: 400 | 401 | 403 | 404 | 500 | 503;
};
/**
 * Duplicates an existing automation. The requesting user must be the owner of the automation or have at least one of the following scopes: `automations`, `admin.automations`, `automations.private` or `automations.shared`.
 *
 * @param id The unique identifier for the automation.
 * @param body an object with the body content
 * @throws CopyAutomationHttpError
 */
declare function copyAutomation(id: string, body: {
  /** Name of the new automation. */name: string;
}, options?: ApiCallOptions): Promise<CopyAutomationHttpResponse>;
type CopyAutomationHttpResponse = {
  data: {
    /** The unique identifier for the automation. */id?: string;
  };
  headers: Headers;
  status: 201;
};
type CopyAutomationHttpError = {
  data: ErrorResponse;
  headers: Headers;
  status: 400 | 401 | 403 | 404 | 500 | 503;
};
/**
 * Disables an automation so that it cannot be run. To disable an automation, the requesting user must meet at least one of the following conditions:
 * - be the owner of the automation
 * - be assigned one of the following roles: `TenantAdmin`, `AnalyticsAdmin`
 * - have at least one of the following scopes: `admin.automations`, `admin.automations:strict`, `automations.private`, or `automations.shared`
 *
 * @param id The unique identifier for the automation.
 * @throws DisableAutomationHttpError
 */
declare function disableAutomation(id: string, options?: ApiCallOptions): Promise<DisableAutomationHttpResponse>;
type DisableAutomationHttpResponse = {
  data: void;
  headers: Headers;
  status: 204;
};
type DisableAutomationHttpError = {
  data: ErrorResponse;
  headers: Headers;
  status: 400 | 401 | 403 | 404 | 500 | 503;
};
/**
 * Enables an automation so that it can be run. To enable an automation, the requesting user must meet at least one of the following conditions:
 * - be the owner of the automation
 * - be assigned one of the following roles: `AnalyticsAdmin`, `TenantAdmin`
 * - have at least one of the following scopes: `admin.automations`, `admin.automations:strict`, `automations.private`, or `automations.shared`
 *
 * @param id The unique identifier for the automation.
 * @throws EnableAutomationHttpError
 */
declare function enableAutomation(id: string, options?: ApiCallOptions): Promise<EnableAutomationHttpResponse>;
type EnableAutomationHttpResponse = {
  data: void;
  headers: Headers;
  status: 204;
};
type EnableAutomationHttpError = {
  data: ErrorResponse;
  headers: Headers;
  status: 400 | 401 | 403 | 404 | 500 | 503;
};
/**
 * Changes the owner of an automation to another user. This action removes the history and change logs of this automation. All linked connections used in the automation are detached and not moved to the new owner. The requesting user must be assigned one of the following roles: `TenantAdmin`, `AnalyticsAdmin` or have at least one of the following scopes: `admin.automations`, `admin.automations:strict`.
 *
 * @param id The unique identifier for the automation.
 * @param body an object with the body content
 * @throws MoveAutomationHttpError
 */
declare function moveAutomation(id: string, body: {
  /** Unique identifier of the new owner of the automation. */userId: string;
}, options?: ApiCallOptions): Promise<MoveAutomationHttpResponse>;
type MoveAutomationHttpResponse = {
  data: void;
  headers: Headers;
  status: 204;
};
type MoveAutomationHttpError = {
  data: ErrorResponse;
  headers: Headers;
  status: 400 | 401 | 403 | 404 | 500 | 503;
};
/**
 * Retrieves a list of runs for a specific automation. The requesting user must be the owner of the automation, or be assigned the one of roles: `TenantAdmin`, `AnalyticsAdmin`. Alternatively, the user must have at least one of the following scopes: `admin.automation-runs`, `automation-runs.private`, or `automation-runs.shared`.
 *
 * @param id The unique identifier for the automation.
 * @param query an object with query parameters
 * @throws GetAutomationRunsHttpError
 */
declare function getAutomationRuns(id: string, query: {
  /** Allowed filters: `status`, `context`, `startTime`, `title`, `spaceId`, `ownerId`, `executedById`, `billable`. */filter?: string; /** The number of runs to retrieve. */
  limit?: number; /** The field to sort by, with +- prefix indicating sort order. (`?query=-startTime` => sort on the `startTime` field using descending order). */
  sort?: "id" | "status" | "startTime" | "-id" | "-status" | "-startTime" | "+id" | "+status" | "+startTime";
}, options?: ApiCallOptions): Promise<GetAutomationRunsHttpResponse>;
type GetAutomationRunsHttpResponse = {
  data: RunList;
  headers: Headers;
  status: 200;
  prev?: (options?: ApiCallOptions) => Promise<GetAutomationRunsHttpResponse>;
  next?: (options?: ApiCallOptions) => Promise<GetAutomationRunsHttpResponse>;
};
type GetAutomationRunsHttpError = {
  data: ErrorResponse;
  headers: Headers;
  status: 400 | 401 | 403 | 404 | 500 | 503;
};
/**
 * Creates a run for a specific automation. Depending on the space the automation belongs to, the requesting user must meet the following requirement:
 * - Private space: be the owner of the automation and have the `automations.private` scope
 * - Shared space: be editor or operator in shared space and have `automations.shared` scope.
 *
 * @param id The unique identifier for the automation.
 * @param body an object with the body content
 * @throws CreateAutomationRunHttpError
 */
declare function createAutomationRun(id: string, body: RunDetailRequestObject, options?: ApiCallOptions): Promise<CreateAutomationRunHttpResponse>;
type CreateAutomationRunHttpResponse = {
  data: RunDetailResponseObject;
  headers: Headers;
  status: 201;
};
type CreateAutomationRunHttpError = {
  data: ErrorResponse;
  headers: Headers;
  status: 400 | 401 | 403 | 404 | 500 | 503;
};
/**
 * Retrieves a specific run for an automation. Depending on the space the automation belongs to, the requesting user must meet the following requirement:
 * - Private space: be the owner of the automation and have the `automations.private` scope
 * - Shared space: be editor or operator in shared space and have `automations.shared` scope.
 *
 * @param id The unique identifier for the automation.
 * @param runId The unique identifier for the run.
 * @throws GetAutomationRunHttpError
 */
declare function getAutomationRun(id: string, runId: string, options?: ApiCallOptions): Promise<GetAutomationRunHttpResponse>;
type GetAutomationRunHttpResponse = {
  data: RunDetailResponseObject;
  headers: Headers;
  status: 200;
};
type GetAutomationRunHttpError = {
  data: ErrorResponse;
  headers: Headers;
  status: 400 | 401 | 403 | 404 | 500 | 503;
};
/**
 * Retrieves the URL for the debug log of a specific automation run. Depending on the space the automation belongs to, the requesting user must meet the following requirement:
 * - Private space: be the owner of the automation and have the `automations.private` scope
 * - Shared space: be editor or operator in shared space and have `automations.shared` scope.
 *
 * @param id The unique identifier for the automation.
 * @param runId The unique identifier for the run.
 * @throws ExportAutomationRunHttpError
 */
declare function exportAutomationRun(id: string, runId: string, options?: ApiCallOptions): Promise<ExportAutomationRunHttpResponse>;
type ExportAutomationRunHttpResponse = {
  data: {
    url?: string;
  };
  headers: Headers;
  status: 200;
};
type ExportAutomationRunHttpError = {
  data: ErrorResponse;
  headers: Headers;
  status: 400 | 401 | 403 | 404 | 500 | 503;
};
/**
 * Retries a specific run by creating a new run using the same inputs. Depending on the space the automation belongs to, the requesting user must meet the following requirement:
 * - Private space: be the owner of the automation and have the `automations.private` scope
 * - Shared space: be editor or operator in shared space and have `automations.shared` scope.
 *
 * @param id The unique identifier for the automation.
 * @param runId The unique identifier for the run.
 * @throws RetryAutomationRunHttpError
 */
declare function retryAutomationRun(id: string, runId: string, options?: ApiCallOptions): Promise<RetryAutomationRunHttpResponse>;
type RetryAutomationRunHttpResponse = {
  data: void;
  headers: Headers;
  status: 204;
};
type RetryAutomationRunHttpError = {
  data: ErrorResponse;
  headers: Headers;
  status: 400 | 401 | 403 | 404 | 500 | 503;
};
/**
 * Forcefully stops an automation run immediately. Depending on the space the automation belongs to, the requesting user must meet the following requirement:
 * - Private space: be the owner of the automation and have the `automations.private` scope
 * - Shared space: be editor or operator in shared space and have `automations.shared` scope.
 *
 * @param id The unique identifier for the automation.
 * @param runId The unique identifier for the run.
 * @throws StopAutomationRunHttpError
 */
declare function stopAutomationRun(id: string, runId: string, options?: ApiCallOptions): Promise<StopAutomationRunHttpResponse>;
type StopAutomationRunHttpResponse = {
  data: void;
  headers: Headers;
  status: 204;
};
type StopAutomationRunHttpError = {
  data: ErrorResponse;
  headers: Headers;
  status: 400 | 401 | 403 | 404 | 500 | 503;
};
/**
 * Retrieves the debug log for a specific run of an automation. Depending on the space the automation belongs to, the requesting user must meet the following requirement:
 * - Private space: be the owner of the automation and have the `automations.private` scope
 * - Shared space: be editor or operator in shared space and have `automations.shared` scope.
 *
 * @param id The unique identifier for the automation.
 * @param runId The unique identifier for the run.
 * @throws GetAutomationRunDebugHttpError
 */
declare function getAutomationRunDebug(id: string, runId: string, options?: ApiCallOptions): Promise<GetAutomationRunDebugHttpResponse>;
type GetAutomationRunDebugHttpResponse = {
  data: void;
  headers: Headers;
  status: 200;
};
type GetAutomationRunDebugHttpError = {
  data: ErrorResponse;
  headers: Headers;
  status: 400 | 401 | 403 | 404 | 500 | 503;
};
/**
 * Clears the cache for workflows/automations api requests.
 */
declare function clearCache(): void;
type AutomationsAPI = {
  /**
   * Retrieves a list of the automations that the requesting user has access to.
   *
   * @param query an object with query parameters
   * @throws GetAutomationsHttpError
   */
  getAutomations: typeof getAutomations;
  /**
   * Creates a new automation. The requesting user must be assigned the `AutomationCreator` role or have at least one of the following scopes: `automations`, `admin.automations`, `automations.private` or `automations.shared`.
   *
   * @param body an object with the body content
   * @throws CreateAutomationHttpError
   */
  createAutomation: typeof createAutomation;
  /**
   * Retrieves the global automation settings for the tenant.
   *
   * @throws GetAutomationsSettingsHttpError
   */
  getAutomationsSettings: typeof getAutomationsSettings;
  /**
   * Updates the global automation settings for the tenant.
   *
   * @param body an object with the body content
   * @throws UpdateAutomationsSettingsHttpError
   */
  updateAutomationsSettings: typeof updateAutomationsSettings;
  /**
   * Retrieves paginated usage metrics for automations. The requesting user must be assigned the `TenantAdmin` or `AnalyticsAdmin` role.
   *
   * @param query an object with query parameters
   * @throws GetAutomationsUsageMetricsHttpError
   */
  getAutomationsUsageMetrics: typeof getAutomationsUsageMetrics;
  /**
   * Deletes an automation. The requesting user must meet at least one of the following conditions:
   * - be the owner of the automation
   * - be assigned one of the following roles: `AnalyticsAdmin`, `TenantAdmin`
   * - have at least one of the following scopes: `admin.automations`, `admin.automations:strict`, `automations.private`, or `automations.shared`
   *
   * @param id The unique identifier for the automation.
   * @throws DeleteAutomationHttpError
   */
  deleteAutomation: typeof deleteAutomation;
  /**
   * Retrieves the full definition of an automation. The requesting user must be the owner of the automation and either be assigned one of the roles: `AutomationsCreator`, `TenantAdmin` or have at least one of the following scopes (depending on whether the automation is in a private or shared space): `automations`, `automations.private` or `automations.shared`.
   *
   * @param id The unique identifier for the automation.
   * @throws GetAutomationHttpError
   */
  getAutomation: typeof getAutomation;
  /**
   * Updates the full definition of an automation. The requesting user must be the owner of the automation and either be assigned the `AutomationCreator` role or have at least one of the following scopes: `automations`, `admin.automations`, `automations.private` or `automations.shared`.
   *
   * @param id The unique identifier for the automation.
   * @param body an object with the body content
   * @throws UpdateAutomationHttpError
   */
  updateAutomation: typeof updateAutomation;
  /**
   * Changes the owner of an automation to another user. This action removes the history and change logs of this automation. All linked connections used in the automation are detached and not moved to the new owner. The requesting user must be assigned one of the following roles: `TenantAdmin`, `AnalyticsAdmin` or have at least one of the following scopes: `admin.automations`, `admin.automations:strict`.
   *
   * @param id The unique identifier for the automation.
   * @param body an object with the body content
   * @throws ChangeOwnerAutomationHttpError
   */
  changeOwnerAutomation: typeof changeOwnerAutomation;
  /**
   * Changes the space of an automation by specifying a new space.
   *
   * @param id The unique identifier for the automation.
   * @param body an object with the body content
   * @throws ChangeSpaceAutomationHttpError
   */
  changeSpaceAutomation: typeof changeSpaceAutomation;
  /**
   * Duplicates an existing automation. The requesting user must be the owner of the automation or have at least one of the following scopes: `automations`, `admin.automations`, `automations.private` or `automations.shared`.
   *
   * @param id The unique identifier for the automation.
   * @param body an object with the body content
   * @throws CopyAutomationHttpError
   */
  copyAutomation: typeof copyAutomation;
  /**
   * Disables an automation so that it cannot be run. To disable an automation, the requesting user must meet at least one of the following conditions:
   * - be the owner of the automation
   * - be assigned one of the following roles: `TenantAdmin`, `AnalyticsAdmin`
   * - have at least one of the following scopes: `admin.automations`, `admin.automations:strict`, `automations.private`, or `automations.shared`
   *
   * @param id The unique identifier for the automation.
   * @throws DisableAutomationHttpError
   */
  disableAutomation: typeof disableAutomation;
  /**
   * Enables an automation so that it can be run. To enable an automation, the requesting user must meet at least one of the following conditions:
   * - be the owner of the automation
   * - be assigned one of the following roles: `AnalyticsAdmin`, `TenantAdmin`
   * - have at least one of the following scopes: `admin.automations`, `admin.automations:strict`, `automations.private`, or `automations.shared`
   *
   * @param id The unique identifier for the automation.
   * @throws EnableAutomationHttpError
   */
  enableAutomation: typeof enableAutomation;
  /**
   * Changes the owner of an automation to another user. This action removes the history and change logs of this automation. All linked connections used in the automation are detached and not moved to the new owner. The requesting user must be assigned one of the following roles: `TenantAdmin`, `AnalyticsAdmin` or have at least one of the following scopes: `admin.automations`, `admin.automations:strict`.
   *
   * @param id The unique identifier for the automation.
   * @param body an object with the body content
   * @throws MoveAutomationHttpError
   */
  moveAutomation: typeof moveAutomation;
  /**
   * Retrieves a list of runs for a specific automation. The requesting user must be the owner of the automation, or be assigned the one of roles: `TenantAdmin`, `AnalyticsAdmin`. Alternatively, the user must have at least one of the following scopes: `admin.automation-runs`, `automation-runs.private`, or `automation-runs.shared`.
   *
   * @param id The unique identifier for the automation.
   * @param query an object with query parameters
   * @throws GetAutomationRunsHttpError
   */
  getAutomationRuns: typeof getAutomationRuns;
  /**
   * Creates a run for a specific automation. Depending on the space the automation belongs to, the requesting user must meet the following requirement:
   * - Private space: be the owner of the automation and have the `automations.private` scope
   * - Shared space: be editor or operator in shared space and have `automations.shared` scope.
   *
   * @param id The unique identifier for the automation.
   * @param body an object with the body content
   * @throws CreateAutomationRunHttpError
   */
  createAutomationRun: typeof createAutomationRun;
  /**
   * Retrieves a specific run for an automation. Depending on the space the automation belongs to, the requesting user must meet the following requirement:
   * - Private space: be the owner of the automation and have the `automations.private` scope
   * - Shared space: be editor or operator in shared space and have `automations.shared` scope.
   *
   * @param id The unique identifier for the automation.
   * @param runId The unique identifier for the run.
   * @throws GetAutomationRunHttpError
   */
  getAutomationRun: typeof getAutomationRun;
  /**
   * Retrieves the URL for the debug log of a specific automation run. Depending on the space the automation belongs to, the requesting user must meet the following requirement:
   * - Private space: be the owner of the automation and have the `automations.private` scope
   * - Shared space: be editor or operator in shared space and have `automations.shared` scope.
   *
   * @param id The unique identifier for the automation.
   * @param runId The unique identifier for the run.
   * @throws ExportAutomationRunHttpError
   */
  exportAutomationRun: typeof exportAutomationRun;
  /**
   * Retries a specific run by creating a new run using the same inputs. Depending on the space the automation belongs to, the requesting user must meet the following requirement:
   * - Private space: be the owner of the automation and have the `automations.private` scope
   * - Shared space: be editor or operator in shared space and have `automations.shared` scope.
   *
   * @param id The unique identifier for the automation.
   * @param runId The unique identifier for the run.
   * @throws RetryAutomationRunHttpError
   */
  retryAutomationRun: typeof retryAutomationRun;
  /**
   * Forcefully stops an automation run immediately. Depending on the space the automation belongs to, the requesting user must meet the following requirement:
   * - Private space: be the owner of the automation and have the `automations.private` scope
   * - Shared space: be editor or operator in shared space and have `automations.shared` scope.
   *
   * @param id The unique identifier for the automation.
   * @param runId The unique identifier for the run.
   * @throws StopAutomationRunHttpError
   */
  stopAutomationRun: typeof stopAutomationRun;
  /**
   * Retrieves the debug log for a specific run of an automation. Depending on the space the automation belongs to, the requesting user must meet the following requirement:
   * - Private space: be the owner of the automation and have the `automations.private` scope
   * - Shared space: be editor or operator in shared space and have `automations.shared` scope.
   *
   * @param id The unique identifier for the automation.
   * @param runId The unique identifier for the run.
   * @throws GetAutomationRunDebugHttpError
   */
  getAutomationRunDebug: typeof getAutomationRunDebug;
  /**
   * Clears the cache for automations api requests.
   */
  clearCache: typeof clearCache;
};
/**
 * Functions for the automations api
 */
declare const automationsExport: AutomationsAPI;
//#endregion
export { AutomationDetailRequestObject, AutomationDetailResponseObject, AutomationDetailUpdateRequestObject, AutomationList, AutomationListObject, AutomationUsageObject, AutomationsAPI, ChangeOwnerAutomationHttpError, ChangeOwnerAutomationHttpResponse, ChangeSpaceAutomationHttpError, ChangeSpaceAutomationHttpResponse, CopyAutomationHttpError, CopyAutomationHttpResponse, CreateAutomationHttpError, CreateAutomationHttpResponse, CreateAutomationRunHttpError, CreateAutomationRunHttpResponse, DeleteAutomationHttpError, DeleteAutomationHttpResponse, DisableAutomationHttpError, DisableAutomationHttpResponse, EnableAutomationHttpError, EnableAutomationHttpResponse, Error, ErrorResponse, ExportAutomationRunHttpError, ExportAutomationRunHttpResponse, GetAutomationHttpError, GetAutomationHttpResponse, GetAutomationRunDebugHttpError, GetAutomationRunDebugHttpResponse, GetAutomationRunHttpError, GetAutomationRunHttpResponse, GetAutomationRunsHttpError, GetAutomationRunsHttpResponse, GetAutomationsHttpError, GetAutomationsHttpResponse, GetAutomationsSettingsHttpError, GetAutomationsSettingsHttpResponse, GetAutomationsUsageMetricsHttpError, GetAutomationsUsageMetricsHttpResponse, Links, MoveAutomationHttpError, MoveAutomationHttpResponse, PaginationLink, RetryAutomationRunHttpError, RetryAutomationRunHttpResponse, RunDetailRequestObject, RunDetailResponseObject, RunList, RunListObject, ScheduleRequestObject, ScheduleResponseObject, SettingsObject, StopAutomationRunHttpError, StopAutomationRunHttpResponse, UpdateAutomationHttpError, UpdateAutomationHttpResponse, UpdateAutomationsSettingsHttpError, UpdateAutomationsSettingsHttpResponse, UsageList, UsageObject, changeOwnerAutomation, changeSpaceAutomation, clearCache, copyAutomation, createAutomation, createAutomationRun, automationsExport as default, deleteAutomation, disableAutomation, enableAutomation, exportAutomationRun, getAutomation, getAutomationRun, getAutomationRunDebug, getAutomationRuns, getAutomations, getAutomationsSettings, getAutomationsUsageMetrics, moveAutomation, retryAutomationRun, stopAutomationRun, automations_d_exports as t, updateAutomation, updateAutomationsSettings };