name: Publish NPM Package

permissions:
  contents: read

on:
  push:
    tags:
      - "v*.*.*"

jobs:
  publish-npm:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v7
        with:
          fetch-depth: 0

      - name: Set up Node.js
        uses: actions/setup-node@v7
        with:
          node-version: 24
          registry-url: "https://registry.npmjs.org"
          package-manager-cache: false # never use caching in release builds, as it can cause issues with package resolution

      - name: Set version and publish
        run: |
          VERSION=$(git describe --tags --abbrev=7 --match "v*")
          VERSION=${VERSION#v}
          echo "version is $VERSION"
          jq --arg version "$VERSION" '.version = $version' package.json > temp.json && mv temp.json package.json
          cat package.json
          # Set the default user-agent.
          ls ./chunks >/dev/null || (echo "Missing chunks directory!" && exit 1)
          find ./chunks -type f -exec sed -i.bak -e "s;defaultUserAgent = \"qlik-api/latest\";defaultUserAgent = \"qlik-api/$VERSION\";g" -- {} +
          rm -f ./chunks/*.bak
          # Publish npm package
          npm publish
